---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos
    driver_config:
      require_chef_omnibus: 11.12.8
      network:
      -  ["private_network", {ip: "33.33.33.33"}]

suites:
  - name: default
    run_list:
      - recipe[webServer::default]
    attributes:
